#!/usr/bin/env bash
# script to give information about a file
file=school
if [ -e $file ]; then
	echo "School file exists"
	if [ -s $file ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file ]; then
		echo "school is a regular file"
	fi
else
	echo "School file does not exist"
fi
